import type { RoleClass } from "./core";
import * as characters from "./characters";

const ROLE_CLASS_LIST: readonly RoleClass[] = [
  characters.Acrobat,
  characters.Alsaahir,
  characters.Artist,
  characters.Atheist,
  characters.Balloonist,
  characters.Baron,
  characters.Boffin,
  characters.Butler,
  characters.Cerenovus,
  characters.Chambermaid,
  characters.Chef,
  characters.Clockmaker,
  characters.Courtier,
  characters.DevilsAdvocate,
  characters.Dreamer,
  characters.Drunk,
  characters.Damsel,
  characters.Empath,
  characters.Exorcist,
  characters.EvilTwin,
  characters.FangGu,
  characters.Flowergirl,
  characters.FortuneTeller,
  characters.Gambler,
  characters.Golem,
  characters.Goblin,
  characters.Godfather,
  characters.Gossip,
  characters.Hermit,
  characters.Imp,
  characters.Investigator,
  characters.Juggler,
  characters.Kazali,
  characters.Klutz,
  characters.Knight,
  characters.Legionary,
  characters.Legion,
  characters.Leviathan,
  characters.Librarian,
  characters.LordOfTyphon,
  characters.LunarProdigy,
  characters.Lunatic,
  characters.Marionette,
  characters.Mathematician,
  characters.Mayor,
  characters.Monk,
  characters.Mutant,
  characters.Nightwatchman,
  characters.NoDashii,
  characters.Noble,
  characters.Oracle,
  characters.Philosopher,
  characters.PitHag,
  characters.Po,
  characters.Poisoner,
  characters.Politician,
  characters.PoppyGrower,
  characters.Princess,
  characters.Pukka,
  characters.Puzzlemaster,
  characters.Ravenkeeper,
  characters.Recluse,
  characters.Riot,
  characters.Sage,
  characters.Saint,
  characters.Savant,
  characters.ScarletWoman,
  characters.Seamstress,
  characters.Shugenja,
  characters.Slayer,
  characters.SnakeCharmer,
  characters.Soldier,
  characters.SolarProdigy,
  characters.Spy,
  characters.Steward,
  characters.Sweetheart,
  characters.TeaLady,
  characters.Undertaker,
  characters.VillageIdiot,
  characters.Virgin,
  characters.Vigormortis,
  characters.Vortox,
  characters.Washerwoman,
  characters.Widow,
  characters.Witch,
  characters.Xaan,
];

export const ROLE_CLASSES: ReadonlyMap<string, RoleClass> = new Map(ROLE_CLASS_LIST.map((cls) => [cls.roleName, cls]));

export function roleByName(name: string): RoleClass {
  const cls = ROLE_CLASSES.get(name);
  if (cls === undefined) throw new Error(`Unknown role: ${name}`);
  return cls;
}
