name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy:
    name: Build and deploy site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7.0.0

      - name: Setup bun
        uses: oven-sh/setup-bun@v2.2.0
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build webapp
        env:
          BASE_PATH: /botc-solvers/
        run: bun run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./browser-dist
          keep_files: true
